"""Update models to match current schema
Revision ID: 1e025f228445
Revises: 20231115
Create Date: 2025-11-09 07:45:03.100581
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "1e025f228445"
down_revision = "20231115"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually create ENUM types for better idempotency (PostgreSQL only)
    if op.get_bind().dialect.name == "postgresql":
        op.execute("""
            DO $$ BEGIN
                CREATE TYPE producttype AS ENUM ('subscription', 'one_time');
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
            DO $$ BEGIN
                CREATE TYPE subscriptiontier AS ENUM ('free', 'pro', 'enterprise');
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
            DO $$ BEGIN
                CREATE TYPE voiceprovider AS ENUM ('openai', 'google', 'aws_polly', 'azure', 'eleven_labs');
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
            DO $$ BEGIN
                CREATE TYPE conversionmode AS ENUM ('full', 'summary_explanation');
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
        """)

    # Create products table using raw SQL to avoid SQLAlchemy's automatic ENUM creation
    op.execute("""
        CREATE TABLE IF NOT EXISTS products (
            id SERIAL PRIMARY KEY,
            paddle_product_id VARCHAR(255) NOT NULL UNIQUE,
            name VARCHAR(255) NOT NULL,
            description TEXT,
            type producttype NOT NULL,
            price NUMERIC(10, 2),
            currency VARCHAR(3),
            credits_included INTEGER,
            subscription_tier subscriptiontier,
            is_active BOOLEAN DEFAULT TRUE,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITH TIME ZONE
        )
    """)

    try:
        op.create_index(op.f("ix_products_id"), "products", ["id"], unique=False)
    except Exception:
        pass

    # Create subscriptions table using raw SQL
    op.execute("""
        CREATE TABLE IF NOT EXISTS subscriptions (
            id SERIAL PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id),
            product_id INTEGER NOT NULL REFERENCES products(id),
            paddle_subscription_id VARCHAR(255) UNIQUE,
            status VARCHAR(50),
            next_billing_date TIMESTAMP WITH TIME ZONE,
            cancelled_at TIMESTAMP WITH TIME ZONE,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITH TIME ZONE
        )
    """)

    try:
        op.create_index(
            op.f("ix_subscriptions_id"), "subscriptions", ["id"], unique=False
        )
    except Exception:
        pass

    # Create transactions table using raw SQL
    op.execute("""
        CREATE TABLE IF NOT EXISTS transactions (
            id SERIAL PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id),
            product_id INTEGER REFERENCES products(id),
            paddle_transaction_id VARCHAR(255) NOT NULL UNIQUE,
            amount NUMERIC(10, 2) NOT NULL,
            currency VARCHAR(3),
            status VARCHAR(50),
            credits_added INTEGER,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
        )
    """)

    try:
        op.create_index(
            op.f("ix_transactions_id"), "transactions", ["id"], unique=False
        )
    except Exception:
        pass

    # Idempotently add columns to jobs table
    _idempotent_add_column(
        "jobs", sa.Column("original_filename", sa.String(length=255), nullable=False)
    )
    _idempotent_add_column(
        "jobs", sa.Column("pdf_s3_url", sa.String(length=1000), nullable=True)
    )
    _idempotent_add_column(
        "jobs", sa.Column("audio_s3_url", sa.String(length=1000), nullable=True)
    )
    _idempotent_add_column(
        "jobs", sa.Column("progress_percentage", sa.Integer(), nullable=True)
    )
    _idempotent_add_column("jobs", sa.Column("error_message", sa.Text(), nullable=True))

    # Add ENUM columns for PostgreSQL; for SQLite use standard sa.Column via _idempotent_add_column
    if op.get_bind().dialect.name == "postgresql":
        op.execute("""
            DO $$ BEGIN
                ALTER TABLE jobs ADD COLUMN voice_provider voiceprovider;
            EXCEPTION
                WHEN duplicate_column THEN null;
            END $$;
        """)
    else:
        # SQLite doesn't support custom types, use VARCHAR or similar if needed, 
        # but SQLAlchemy models handle mapping.
        _idempotent_add_column("jobs", sa.Column("voice_provider", sa.String(), nullable=True))

    _idempotent_add_column(
        "jobs", sa.Column("voice_type", sa.String(length=50), nullable=True)
    )
    _idempotent_add_column(
        "jobs",
        sa.Column("reading_speed", sa.Numeric(precision=3, scale=2), nullable=True),
    )
    _idempotent_add_column(
        "jobs", sa.Column("include_summary", sa.Boolean(), nullable=True)
    )

    # Add conversion_mode ENUM column for PostgreSQL
    if op.get_bind().dialect.name == "postgresql":
        op.execute("""
            DO $$ BEGIN
                ALTER TABLE jobs ADD COLUMN conversion_mode conversionmode;
            EXCEPTION
                WHEN duplicate_column THEN null;
            END $$;
        """)
    else:
        _idempotent_add_column("jobs", sa.Column("conversion_mode", sa.String(), nullable=True))

    _idempotent_add_column(
        "jobs",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
    )
    _idempotent_add_column(
        "jobs", sa.Column("started_at", sa.DateTime(timezone=True), nullable=True)
    )
    _idempotent_add_column(
        "jobs", sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True)
    )

    # Modify existing columns in jobs table (do this carefully to avoid errors)
    try:
        op.alter_column("jobs", "user_id", existing_type=sa.INTEGER(), nullable=False)
    except Exception:
        pass

    try:
        op.alter_column(
            "jobs", "pdf_s3_key", existing_type=sa.VARCHAR(), nullable=False
        )
    except Exception:
        pass

    # Idempotently add columns to users table
    _idempotent_add_column(
        "users", sa.Column("auth_provider_id", sa.String(length=255), nullable=False)
    )
    _idempotent_add_column(
        "users", sa.Column("first_name", sa.String(length=100), nullable=True)
    )
    _idempotent_add_column(
        "users", sa.Column("last_name", sa.String(length=100), nullable=True)
    )

    # Add subscription_tier ENUM column for PostgreSQL
    if op.get_bind().dialect.name == "postgresql":
        op.execute("""
            DO $$ BEGIN
                ALTER TABLE users ADD COLUMN subscription_tier subscriptiontier;
            EXCEPTION
                WHEN duplicate_column THEN null;
            END $$;
        """)
    else:
        _idempotent_add_column("users", sa.Column("subscription_tier", sa.String(), nullable=True))

    _idempotent_add_column(
        "users", sa.Column("paddle_customer_id", sa.String(length=255), nullable=True)
    )
    _idempotent_add_column(
        "users", sa.Column("one_time_credits", sa.Integer(), nullable=True)
    )
    _idempotent_add_column(
        "users", sa.Column("monthly_credits_used", sa.Integer(), nullable=True)
    )
    _idempotent_add_column(
        "users",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
    )
    _idempotent_add_column(
        "users", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )

    try:
        op.create_index(
            op.f("ix_users_auth_provider_id"),
            "users",
            ["auth_provider_id"],
            unique=True,
        )
    except Exception:
        # Index probably already exists
        pass

    try:
        op.drop_column("users", "hashed_password")
        op.drop_column("users", "is_active")
    except Exception:
        # Columns probably don't exist
        pass
    # ### end Alembic commands ###


def _idempotent_add_column(table_name, column):
    from sqlalchemy.exc import InternalError

    try:
        op.add_column(table_name, column)
    except InternalError as e:
        # Error code for "duplicate column" in PostgreSQL is 42701
        if "duplicate column" in str(e) or "column already exists" in str(e).lower():
            print(f"Column {column.name} already exists on {table_name}, skipping.")
        else:
            raise


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_active", sa.BOOLEAN(), nullable=True))
    op.add_column("users", sa.Column("hashed_password", sa.VARCHAR(), nullable=False))
    op.drop_index(op.f("ix_users_auth_provider_id"), table_name="users")
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.drop_column("users", "monthly_credits_used")
    op.drop_column("users", "one_time_credits")
    op.drop_column("users", "paddle_customer_id")
    op.drop_column("users", "subscription_tier")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_column("users", "auth_provider_id")
    op.alter_column("jobs", "pdf_s3_key", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("jobs", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("jobs", "completed_at")
    op.drop_column("jobs", "started_at")
    op.drop_column("jobs", "created_at")
    op.drop_column("jobs", "conversion_mode")
    op.drop_column("jobs", "include_summary")
    op.drop_column("jobs", "reading_speed")
    op.drop_column("jobs", "voice_type")
    op.drop_column("jobs", "voice_provider")
    op.drop_column("jobs", "error_message")
    op.drop_column("jobs", "progress_percentage")
    op.drop_column("jobs", "audio_s3_url")
    op.drop_column("jobs", "pdf_s3_url")
    op.drop_column("jobs", "original_filename")
    op.drop_index(op.f("ix_transactions_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_subscriptions_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_products_id"), table_name="products")
    op.drop_table("products")
    sa.Enum(name="producttype").drop(op.get_bind())
    sa.Enum(name="subscriptiontier").drop(op.get_bind())
    sa.Enum(name="voiceprovider").drop(op.get_bind())
    sa.Enum(name="conversionmode").drop(op.get_bind())
    # ### end Alembic commands ###
