"""Add usage tracking and webhook events
Revision ID: a17b877b1ff5
Revises: a33adb61776b
Create Date: 2025-12-23 05:17:18.092047
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17b877b1ff5'
down_revision = 'a33adb61776b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paddle_event_id', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_id'), 'webhook_events', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_events_paddle_event_id'), 'webhook_events', ['paddle_event_id'], unique=False)
    
    op.add_column('jobs', sa.Column('chars_processed', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('credit_balance', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credit_balance')
    op.drop_column('jobs', 'tokens_used')
    op.drop_column('jobs', 'chars_processed')
    op.drop_index(op.f('ix_webhook_events_paddle_event_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
