"""add_estimated_cost_and_update_modes
Revision ID: a33adb61776b
Revises: 1e025f228445
Create Date: 2025-12-19 06:12:40.685387
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33adb61776b'
down_revision = '1e025f228445'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Update ConversionMode ENUM (PostgreSQL only)
    if op.get_bind().dialect.name == "postgresql":
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE conversionmode ADD VALUE IF NOT EXISTS 'summary'")
            op.execute("ALTER TYPE conversionmode ADD VALUE IF NOT EXISTS 'explanation'")

    op.add_column('jobs', sa.Column('estimated_cost', sa.Numeric(precision=10, scale=6), nullable=True))
    op.alter_column('jobs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jobs', 'pdf_s3_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    op.alter_column('products', 'subscription_tier',
               existing_type=sa.NUMERIC(),
               type_=sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='subscriptiontier'),
               existing_nullable=True)
    op.alter_column('products', 'type',
               existing_type=sa.NUMERIC(),
               type_=sa.Enum('SUBSCRIPTION', 'ONE_TIME', name='producttype'),
               existing_nullable=False)
    op.alter_column('products', 'created_at',
               existing_type=sa.NUMERIC(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('products', 'updated_at',
               existing_type=sa.NUMERIC(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_unique_constraint(None, 'products', ['paddle_product_id'])
    op.alter_column('subscriptions', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    op.alter_column('subscriptions', 'next_billing_date',
               existing_type=sa.NUMERIC(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('subscriptions', 'cancelled_at',
               existing_type=sa.NUMERIC(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('subscriptions', 'created_at',
               existing_type=sa.NUMERIC(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('subscriptions', 'updated_at',
               existing_type=sa.NUMERIC(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_unique_constraint(None, 'subscriptions', ['paddle_subscription_id'])
    op.alter_column('transactions', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    op.alter_column('transactions', 'created_at',
               existing_type=sa.NUMERIC(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_unique_constraint(None, 'transactions', ['paddle_transaction_id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.NUMERIC(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('transactions', 'id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.alter_column('subscriptions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('subscriptions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.NUMERIC(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('subscriptions', 'cancelled_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('subscriptions', 'next_billing_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('subscriptions', 'id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'products', type_='unique')
    op.alter_column('products', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.NUMERIC(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('products', 'type',
               existing_type=sa.Enum('SUBSCRIPTION', 'ONE_TIME', name='producttype'),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('products', 'subscription_tier',
               existing_type=sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='subscriptiontier'),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('products', 'id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=True,
               autoincrement=True)
    op.alter_column('jobs', 'pdf_s3_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('jobs', 'estimated_cost')
    # ### end Alembic commands ###
